### ISSUE TITLE
import errand error  /var/vcap/jobs/import/bin/run: line 10: syntax error near unexpected token `}'

### ISSUE THREAD

**Issue by riddhichheda** [shieldproject/shield-boshrelease#179]
Hi All,
I am trying to deploy Shield v8.3.0 on Bosh . Shield Deployment is successful. After deployment while running import errand , it gives below error: 

Instance   import/d102xxxx-xxxx-xxxx-xxxx-xxxx142e3d8a
Exit Code  2
Stdout     -
Stderr     /var/vcap/jobs/import/bin/run: line 10: syntax error near unexpected token `}'

1 errand(s)

Errand 'import' completed with error (exit code 2)

Exit code 1

Many Thanks.

**Comment by jhunt** [comment]
That would be because this snippet here: https://github.com/shieldproject/shield-boshrelease/blob/master/jobs/import/templates/bin/run#L11-L17 is creating empty sub bodies if you are _not_ generating a token for import -- i.e. the `generate_token` property is left at its default setting of 'false'.

Try setting `generate_token` in your BOSH deployment manifest to "true" (and set the username, password, etc. properties to their correct values).

**Comment by riddhichheda** [comment]
Thanks for the help. My issue is resolved.

**Comment by riddhichheda** [comment]
Hi team,
I am facing this same issue in shield release 8.7.0 as well. And the release 8.7.4 does not have the latest release in the shield manifest file.
Can you please help me here.
Thanks in advance.

**Comment by riddhichheda** [comment]
Hi Team ,
Can you please advice here after running import errand, it gives below error:
Stderr     !!! <stdin>: Tenant 'Mysql-ccdb', data system 'CCDB', job 'CCDB-Daily' is missing its `retain' attribute

Where to add this missing "retain" attribute and with what value? is there any spec or documentation available ? please suggest.
